name: Automated API tests using Postman CLI

on:
  push:  # Se ejecuta en cada push
    branches:
      - main
  workflow_dispatch: {}  # Permite ejecución manual
  schedule:
    - cron: '0 0 * * 1'  # Se ejecuta semanalmente. Los lunes a media noche

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "33801345-181c803c-a263-4988-9141-4482d833eb4c" -e "33801345-e08ef3e0-e06f-4b5c-936b-179df25cea75"
